apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSTJPSVg0S29jbW93RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRFeU1ESXdPVEV4TWpWYUZ3MHpOVEV4TXpBd09URTJNalZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURHZm9HcDZkQW4vWEgyaFh6QmR1WWpTNlJRYklCY3RhazY2SVh4alVBMFBtV2xyUTdWT2Qwb0lmWXQKR1didXk0TWE2Um8wbm9kcGNBektjWHlvQk5iVmNsSVZIMGl2WGVWczkwajVDd3d6bXFMMnFMdE5SYmUwbVJicApQdjhxWk5mU0VIVmlvNXJUOHZkK3lCUzRCb0t5VHlIVmN3UHNubHJBTGp5b1pQbEgxUXY0ZGJoRDFGaGJNcDR6Clc2b0RxVm5IM2pBdFhlbTNTVEdkWXhSK2QrM0xlZGRxa1lnbk5uNmJSSTU0VkNYZEg5S0tWQWhCZHI0eS9meHUKd0cyaklxUWNxd3l1enozd2t3REFPdHBJZ3l2SWZWU2h0UVl4eVVRajcvV1FqTHRHTVdlMHVPMVpvY2o1dXRndQovZWRpNUJ4Zk9NelBVTVdRU3lsSlFaOTk3N3pGQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSMWZUcGlwbEtCdFZ5QWFUVDhjaGtzdmgxME5EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjh3ako3K1pVNwp6blVOV3diV3gwMUFiV1Rzc3lJaWJQYTdGTEQyWHJFQWFHNEV0UlRjZmtEMjY5Zjd2M2pJV1RUblZacVZZQzV4CjJtMUxIRFRlN3dOQ0lPRDZMYmhGalFMQ2lNbnpsYkRtQXNKbFY3a3ZSOW85cUxXbjN1ejFwMTRWOHk4d2d5ckIKcExOaHBlTHh4MlZqQ0did3pURmZKRHlwWTdIT3NzUCtxbVl0S2xvUlR5L2FXTWRkeS9DLzlJeGdwUWlZWldKdgorVDFncTJ2RTNFY3Q4Skt4WEg5dC90dmMrWHRCdDNVUGNGZjdCa3V2cGFDQnM1TXBmdjhqbU9mRG1NODVwdklQCndzVHh5THZ4djBEbnNBcTZadGVSVE5CdGptYUppemJJRGpReUk1Y21BSm1HM2hXOGMzdDlMSm5PTHpYQjJUaVQKNlRpSzJXRFlMV254Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://F7FB750153A2A14B3ED87E3CE76A209C.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
    user: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
  name: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
current-context: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
kind: Config
users:
- name: arn:aws:eks:us-east-1:430118830222:cluster/multi-region
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - multi-region
      - --output
      - json
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
